SELECT 
    t.TABLE_NAME AS 'table',
    c.COLUMN_NAME AS 'name',
    c.ORDINAL_POSITION AS 'pos',
    c.DATA_TYPE AS 'type',
    c.COLUMN_DEFAULT AS '_default',
    CASE
        WHEN c.IS_NULLABLE = 'YES' THEN TRUE
        ELSE FALSE
    END AS 'nullable',
    k.REFERENCED_TABLE_NAME AS 'ref_table',
    k.REFERENCED_COLUMN_NAME AS 'ref_col'
FROM
    INFORMATION_SCHEMA.TABLES t
        LEFT JOIN
    INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_SCHEMA = c.TABLE_SCHEMA
        AND t.TABLE_NAME = c.TABLE_NAME
        LEFT JOIN
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE k ON c.TABLE_SCHEMA = k.TABLE_SCHEMA
        AND c.TABLE_NAME = k.TABLE_NAME
        AND c.COLUMN_NAME = k.COLUMN_NAME
        LEFT JOIN
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS n ON k.CONSTRAINT_SCHEMA = n.CONSTRAINT_SCHEMA
        AND k.CONSTRAINT_NAME = n.CONSTRAINT_NAME
        AND k.TABLE_SCHEMA = n.TABLE_SCHEMA
        AND k.TABLE_NAME = n.TABLE_NAME
WHERE
    t.TABLE_TYPE = 'BASE TABLE'
        AND t.TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA' , 'mysql', 'performance_schema')
        AND t.TABLE_SCHEMA = 'chatapp';